### ISSUE TITLE
Emphasize that only *working* code should be deployed

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/gh-pages-deployment-guide#11]
`gh-pages` is not a replacement for `grunt serve`.

`gh-pages` is a **production** environment.

**NEVER** test code in production environments.

**ONLY** deploy when code is verified as working.

**Comment by jordanallain** [comment]
This is solid advice, should I add it to workflow rules or make it its own sub-section?

**Comment by jrhorn424** [comment]
It's not about workflow per se. Make a section called Commandments?

**Comment by jordanallain** [comment]
Sounds good, adding this today unless anyone objects.
