### ISSUE TITLE
Deployment guides should require a PR (or issue) with a link to a deployed site

### ISSUE THREAD

**Issue by jrhorn424** [ga-wdi-boston/gh-pages-deployment-guide#12]
https://github.com/ga-wdi-boston/instructors/issues/55

**Comment by jordanallain** [comment]
Do we want to add this as a deliverable to this study?

**Comment by jrhorn424** [comment]
@jordanallain Yes. What do you think is best? A PR with a text file (pick a good name for the developers) or an issue with a hyperlink? I'm leaning toward a PR.

**Comment by jordanallain** [comment]
PR fits in nicely with the process that the developers are familiar with by this point. I can add a `url.md` file to the repo where they will place the link.

**Comment by jrhorn424** [comment]
Thank you, great suggestion.
