### ISSUE TITLE
Please add guidelines for multiple/subsequent deployments

### ISSUE THREAD

**Issue by kopius** [ga-wdi-boston/gh-pages-deployment-guide#6]
These steps work perfectly when first deploying, but when making multiple deployments on the same project and a remote 'gh-pages' branch already exists, it is unclear which steps can or should be omitted in subsequent deployments. Please add guidelines to clarify this. Thank you!

**Comment by raq929** [comment]
@gaand, @jrhorn424 What's our preferred workflow for redeployment? Rebase gh-pages on master or delete gh-pages and re-create it from master? (Or something else?)

**Comment by gaand** [comment]
I lean toward rebase.

**Comment by raq929** [comment]
Given the problems our cohort is having, I strongly agree. I'll update before project 2.

**Comment by jrhorn424** [comment]
I believe this has been dealt with? See: https://github.com/ga-wdi-boston/browser-template/blob/master/grunt/shell.js#L24

**Comment by jrhorn424** [comment]
I believe this can be closed as of 8ae52ed4564b0c948c829fda0af145e819daa025

**Comment by gaand** [comment]
@jrhorn424 Agreed and closing.
